DROP DATABASE IF EXISTS worm;
CREATE DATABASE worm;
USE worm;

CREATE TABLE player (
	username VARCHAR(20) PRIMARY KEY,
	password VARCHAR(500),
	session VARCHAR(30)
)ENGINE=InnoDB;

CREATE TABLE score (
    ID INT AUTO_INCREMENT PRIMARY KEY,
	player VARCHAR(20),
	score INT NOT NULL,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;
