CREATE DATABASE worm;
USE worm;

CREATE TABLE player (
    ID INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(20),
	password VARCHAR(500)
)ENGINE=InnoDB;

CREATE TABLE score (
    ID INT AUTO_INCREMENT PRIMARY KEY,
	player VARCHAR(20),
	score INT NOT NULL,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;
